import AdminPanel from "@/components/admin/adminSideBar/AdminPanel";
import AdminGuard from "@/components/admin/AdminGuard";

export const metadata = {
  title: "Admin Dashboard",
  description: "Generated by Next.js",
};

export default function AdminLayout({ children }) {
  return (
    <AdminGuard>
      <div
        style={{
          display: "flex",
          minHeight: "100vh",
          backgroundColor: "#f8f9fa",
          gap: "20px",
        }}
      >
        <AdminPanel />

        <main style={{ flex: 1 }}>
          {children}
        </main>
      </div>
    </AdminGuard>
  );
}
